### ISSUE TITLE
Layout breaks if images don't have explicit sizes— need to wait for them to finish loading.

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#10]
Sometimes Bindery doesn't flow content properly and you'll see content overflowing (vertically) on most pages. I've only seen it happen on initial load, but it happens somewhat frequently. If you refresh, things seem to render as expected. Maybe it's due to images not being fully loaded when the script is run?

**Comment by evnbr** [comment]
Yeah I believe you're right, my test cases had explicitly sized images.

**Comment by evnbr** [comment]
This should be fixed alpha 4, it know waits until images are loaded. please reopen if you run into it again.
