### ISSUE TITLE
Full page bleed should be easier to set through CSS

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#11]
I'm trying to use the FullPage rule to display an image that has 100% width and height of the containing page, but it seems like the container has no set height. Do you have an example of how to use this rule to create a full image bleed page?

**Comment by evnbr** [comment]
Not currently, besides just setting the dimensions manually. I think I need to simplify FullPage, because that seems like a common use case and really should work. I imagine you have the same issue with Spread?

**Comment by teddybradford** [comment]
Yeah. Being able to have access to the page's width+height through inheritance (i.e., 100% width/height of parent) will open up a lot of flexibility for styling elements.

**Comment by evnbr** [comment]
This is fixed alpha 4
