### ISSUE TITLE
conflict with bootstrap 

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [evnbr/bindery#118]
**the bug**
In trying to bind a page that's organized with bootstrap 3 grid, Bindery is making one page with no flow to other pages. 

**To Reproduce**
**contents.html**
`
<div id="content" class="col-xs-12 col-sm-12">
  <div class="row">
    <div class="col-xs-4">
      <p>lorem</p>
    </div>
    <div class="col-xs-8">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam euismod enim ut dolor dapibus aliquam. Fusce pulvinar eros massa, id consectetur neque ultrices at. Donec ac nibh fermentum mi elementum tempor vitae consectetur tortor. Nam
        porta fringilla molestie. Etiam ullamcorper vel diam eleifend fringilla. Cras sagittis eleifend nibh vel consequat. Suspendisse posuere mauris leo, eget tincidunt libero vehicula eget. Quisque dictum, dui in tristique vehicula, est metus
        volutpat tellus, et vestibulum mauris eros eget quam. Curabitur ut sagittis purus. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <p>Interdum</p>
    </div>
    <div class="col-xs-8">
      <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel orci nisi. Morbi est velit, varius ut nunc ut, auctor dignissim odio. Aliquam a lacus ligula. Maecenas dictum et quam vitae finibus. Morbi facilisis accumsan mi, sed
        facilisis odio aliquet sed. Donec in lectus in massa pellentesque convallis vitae non magna. Suspendisse non odio id lacus congue rhoncus cursus nec orci. Integer ac quam purus. Nulla pharetra lobortis euismod. Aenean at suscipit est. Donec
        sollicitudin felis eget gravida vestibulum. Vivamus eget purus et massa feugiat lacinia. Proin eu ultricies sem. Donec et sem felis. Praesent turpis nunc, sollicitudin nec pretium eu, vehicula eu lectus. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <p>nostra</p>
    </div>
    <div class="col-xs-8">
      <p>Curabitur ornare mauris sed diam aliquam hendrerit. Aliquam ac sodales sapien. Nulla aliquam faucibus nunc et commodo. In hac habitasse platea dictumst. Morbi a nibh quis ipsum pretium vestibulum nec a mauris. Maecenas imperdiet lacus et ex
        dignissim ullamcorper. In et tortor id nulla faucibus sagittis quis at mi. Duis sollicitudin mattis ligula, nec ultrices leo suscipit vel. Nullam a mauris sagittis, convallis nibh a, gravida libero. Sed a vestibulum odio, sed luctus nisl.
        Vestibulum pharetra non nibh et mattis. Curabitur tempor gravida tincidunt. Nunc sed auctor augue. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <p>risus</p>
    </div>
    <div class="col-xs-8">
      <p>Proin dapibus gravida risus in dapibus. Nulla a libero eget ligula volutpat maximus ut ac metus. Morbi non posuere mi, at dignissim mi. Ut eu consectetur lectus. Nullam gravida porta orci posuere ullamcorper. Integer malesuada lobortis
        elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam tellus eros, auctor sit amet ipsum a, facilisis lobortis magna. Morbi sed eros tellus. Class aptent taciti sociosqu ad litora
        torquent per conubia nostra, per inceptos himenaeos. Proin tempor nulla quis elit dapibus sollicitudin ac vel quam. Donec lacinia turpis at risus sollicitudin aliquet. Integer in enim id felis rutrum pellentesque id ac mi. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <p>risus</p>
    </div>
    <div class="col-xs-8">
      <p>Proin dapibus gravida risus in dapibus. Nulla a libero eget ligula volutpat maximus ut ac metus. Morbi non posuere mi, at dignissim mi. Ut eu consectetur lectus. Nullam gravida porta orci posuere ullamcorper. Integer malesuada lobortis
        elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam tellus eros, auctor sit amet ipsum a, facilisis lobortis magna. Morbi sed eros tellus. Class aptent taciti sociosqu ad litora
        torquent per conubia nostra, per inceptos himenaeos. Proin tempor nulla quis elit dapibus sollicitudin ac vel quam. Donec lacinia turpis at risus sollicitudin aliquet. Integer in enim id felis rutrum pellentesque id ac mi. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <p>risus</p>
    </div>
    <div class="col-xs-8">
      <p>Proin dapibus gravida risus in dapibus. Nulla a libero eget ligula volutpat maximus ut ac metus. Morbi non posuere mi, at dignissim mi. Ut eu consectetur lectus. Nullam gravida porta orci posuere ullamcorper. Integer malesuada lobortis
        elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam tellus eros, auctor sit amet ipsum a, facilisis lobortis magna. Morbi sed eros tellus. Class aptent taciti sociosqu ad litora
        torquent per conubia nostra, per inceptos himenaeos. Proin tempor nulla quis elit dapibus sollicitudin ac vel quam. Donec lacinia turpis at risus sollicitudin aliquet. Integer in enim id felis rutrum pellentesque id ac mi. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <p>risus</p>
    </div>
    <div class="col-xs-8">
      <p>Proin dapibus gravida risus in dapibus. Nulla a libero eget ligula volutpat maximus ut ac metus. Morbi non posuere mi, at dignissim mi. Ut eu consectetur lectus. Nullam gravida porta orci posuere ullamcorper. Integer malesuada lobortis
        elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam tellus eros, auctor sit amet ipsum a, facilisis lobortis magna. Morbi sed eros tellus. Class aptent taciti sociosqu ad litora
        torquent per conubia nostra, per inceptos himenaeos. Proin tempor nulla quis elit dapibus sollicitudin ac vel quam. Donec lacinia turpis at risus sollicitudin aliquet. Integer in enim id felis rutrum pellentesque id ac mi. </p>
    </div>
  </div>
</div>`

**index.html**
`<head>
  <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</head>
<body>
  <script src="https://unpkg.com/bindery@2.3.0"></script>
  <script>
    const instructions = {
      content: {
        selector: '#content',
        url: 'contents.html',
      },
      pageSetup: {
       size: { width: '8.5in', height: '11in' },
       margin: { top: '1in', inner: '1in', outer: '1in', bottom: '1in' },
     },
     rules : [
     Bindery.PageBreak({
            selector: 'h1',
            position: 'after',
            continue: 'next'
          }),
          Bindery.PageBreak({
            selector: 'h2',
            position: 'before',
            continue: 'right'
          }),
     ]
    }
  Bindery.makeBook(instructions);
  </script>
</body>
`

**Expected behavior**
Text was meant to flow across many pages, here it seems it is truncated after 1. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6713092/163694888-132451b8-c55d-4e05-8239-0fa770a04216.png)

**Desktop (please complete the following information):**
 - OS & Browser: [Window 11 & Firefox]
 - bindery.js version [e.g. 2.3.0]

**Additional context**
bootstrap 3 is an older library which I use out of habit over bootstrap 4 or 5, but still works fine in other contexts.

**Comment by evnbr** [comment]
Hi Garrett, thanks for the clear steps, I have a few ideas.

It looks like this version of bootstrap uses `float` for positioning columns, and you have applied columns to the outermost `#content` container. The problem is that `float` takes content out of the normal flow of the page, so when bindery tries to measure the page to detect overflow, it always looks 0px tall.

Some potential workarounds:

1. Remove the column classes from the outermost element. I can't tell if they are doing anything in this example, this might not work for your real site.
   ```
   <div id="content"> ... </div>
   ```

2. Specifically turn off float with an inline style. Again, this seems fine for the example, again might not work for your real site.
   ```
   <div id="content" class="col-xs-12 col-sm-12" style="float: none"> ... </div>
   ```

3. Same as 2, but set it in javascript so it only takes affect when using bindery. This would need to be called somewhere before calling makeBook, ie:
   ```
   document.querySelector("#content").style.float = "none";
   Bindery.makeBook({...});
   ```

4. Use a newer version of boostrap that doesn't rely CSS float. It looks like the most recent versions use `flexbox` which should work better.


Here's a working example of approach #3: https://codepen.io/brsev/pen/YzYRRZe 

Let me know if any of those work for you and best of luck with your book.
