### ISSUE TITLE
PageBreak.continue leads to inconsistent order

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#13]
For certain posts, I display a hero image before the post header (i.e., post title + metadata). I am trying to force the hero image to always appear on the left page, with the post header always appearing to the right of that. There should be no other content on these facing pages (text should flow to the next left facing page after the post header).

I have a set of PageBreak rules as follows:

```js
Bindery.PageBreak({ selector: ".hero-figure", position: "before", continue: "left" }), // force .hero-figure to be on left facing pages
Bindery.PageBreak({ selector: ".post-header", position: "before", continue: "right" }), // force .post-header to be on right facing pages
Bindery.PageBreak({ selector: ".post-header", position: "after", continue: "left" }), // flow content after .post-header onto next page
```

Unfortunately, I end up with a variety of odd results:

![image](https://user-images.githubusercontent.com/3684553/29182439-f10209b6-7dcc-11e7-8e79-ea6957ffc7ce.png)

Sometimes it works:

![image](https://user-images.githubusercontent.com/3684553/29182460-024cebf0-7dcd-11e7-8159-deab3d59c1f6.png)

But this happens a lot:

![image](https://user-images.githubusercontent.com/3684553/29182480-14f776da-7dcd-11e7-80fd-1176ca776d64.png)

Any idea what's causing this? Am I misinterpreting how the PageBreak rule works?

**Comment by evnbr** [comment]
marked as bug. what you describe should certainly work, it should also be identical to:

`Bindery.PageBreak({ selector: ".hero-figure", position: "before", continue: "left" }), `
**`Bindery.PageBreak({ selector: ".hero-figure", position: "after", continue: "right" }), `**
`Bindery.PageBreak({ selector: ".post-header", position: "after", continue: "left" }),`

**Comment by evnbr** [comment]
This should be fixed alpha 4, please lmk if you're still seeing it

**Comment by evnbr** [comment]
Closing this since page *order* no longer seems to be an issue, just extra pages.
