### ISSUE TITLE
FullPage rule seems to mess up PageBreak rules

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#14]
With pagebreak rules set and a fullpage set, the flow appears erratic.

```js
Bindery.PageBreak({ selector: ".hero-figure", position: "both", continue: "both" }),
Bindery.PageBreak({ selector: ".post-header", position: "both", continue: "both" }),
```

with `Bindery.FullPage({ selector: ".hero-figure" }),`

results in:

![image](https://user-images.githubusercontent.com/3684553/29189764-bd0f7760-7de5-11e7-881f-db1f60976868.png)

The purple image is from the previous post, the "1-inch Buttons" is part of .post-header and the image on the right is a .hero-figure.

**Comment by evnbr** [comment]
3 questions

1. what is the intended flow here? based on the rules you describe, I imagine it's 'vote nirva', header, image all on separate pages in that order.

2. what was the original flow here? Assuming: 'vote nirva' image, header, capsule image

3. What would you intend/expect the behavior to be when you set Fullpage and PageBreak on the same selector?

**Comment by teddybradford** [comment]
1. The intended flow is:
  1. Nirva image (own page)
  2. Hero image (own page)
  3. Header (own page)
2. The original flow here is:
  1. Nirva image (part of previous post)
  2. Hero image
  3. Header
3. It appears that when I set the hero image to be a FullPage, Bindery is reordering the elements not according to the order they appear in the HTML.

**Comment by evnbr** [comment]
Ah. I intended it to work a little differently, but i did not make that clear. The FullPage and Spread rules are supposed to pull elements out of the flow, without leaving unsightly gaps where the paragraphs normally leave off— which I think is a legit use case. Maybe I should call them OutOfFlow or something more descriptive?

![image](https://user-images.githubusercontent.com/1024086/29192655-04705016-7dd7-11e7-8f10-39d24585deb5.png)

**Comment by evnbr** [comment]
This should be clearer in alpha 4. you can now do `Bindery.FullBleedPage({selector: 'figure', continue: 'next' })` which continues like you assumed. (or `continue: 'same'` to pull the element out of flow.

let me know if that works

**Comment by teddybradford** [comment]
Awesome!

Couple questions:

1. Given `Bindery.FullBleedPage({ selector: ".hero-figure", continue: "right" })`, should the .hero-figure always appear on the left page?
2. It seems that the FullBleedPage can sometimes contain elements from the previous page, see:
![image](https://user-images.githubusercontent.com/3684553/29293604-b61778cc-8119-11e7-8232-f00542a1366c.png)
The purple Nirva image is not part of the .hero-figure, but is appearing on the same page as it.

**Comment by evnbr** [comment]
1. not necessarily. i think you have two options:
  a. Just add a `Bindery.PageBreak({ selector: ".hero-figure", position: 'before', continue: "left" })`
  b. If that doesn't work, I could add a 'preferred side' option to `Bindery.FullBleedPage`.
2. whoops yep will fix

**Comment by evnbr** [comment]
pushed a build that should fix the extra elements on fullbleedpage, lmk if you still see them.

**Comment by teddybradford** [comment]
I'm using the following rules:
```js
Bindery.PageBreak({ selector: ".hero-figure", position: "before", continue: "right" }),
Bindery.PageBreak({ selector: ".post-header", position: "before", continue: "right" }),
Bindery.PageBreak({ selector: ".post-header", position: "after", continue: "left" }),
Bindery.FullBleedPage({ selector: ".hero-figure", continue: "right" }),
```
I'm expecting:
1. All hero-figures to appear on the left (which they do);
2. All post-headers to appear on the right of hero-figures (they do not, there 2 blank pages in between, see image below);
3. All post content after post-headers to appear on the page after post-header (which they do).

![image](https://user-images.githubusercontent.com/3684553/29378762-4175bc92-828e-11e7-990a-d7a0b748aa42.png)

**Comment by teddybradford** [comment]
Adding a page break to a FullBleed element seems to add a blank spread to the flow.

**Comment by teddybradford** [comment]
Actually, it looks like it might be when 2 page break rules are applied to elements on adjacent pages.

**Comment by evnbr** [comment]
hm that is plausible. it seems like there’s a problem with the code that
detects whether a page is empty, which was causing that overlapping image
problem before.

**Comment by evnbr** [comment]
Pushed a build that should properly detect blank pages. Let me know if you're still running into this.

**Comment by teddybradford** [comment]
Awesome! That seems to have fixed it! 😃

**Comment by evnbr** [comment]
Feel free to reopen if it comes back 😨
