### ISSUE TITLE
Counter replacement isn't applied to FullBleedSpread

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#35]
🙁

**Comment by teddybradford** [comment]
Same issue occurs for FullBleedPage.

**Comment by evnbr** [comment]
My bad for not trying that. Looks like all rules are broken on fullbleedpage. Fix incoming, will push it out tonight.
![image](https://user-images.githubusercontent.com/1024086/30455945-99a52bf8-9956-11e7-9ecb-fb83f33f171c.png)

**Comment by teddybradford** [comment]
Awesome! Thank you! 😃
