### ISSUE TITLE
Print preview on load page, by default

### ISSUE THREAD

**Issue by YuccaV2** [evnbr/bindery#48]
Is it possible to have the print preview view first when loading the page (1 page / sheet) ?

**Comment by evnbr** [comment]
Yes, been planning on making the default print options configurable. Will push out a new version sometime next week.

**Comment by evnbr** [comment]
Resolved by #49 - See [the new `printSetup` section](https://evanbrooks.info/bindery/docs/#printsetup) in the docs

Feel free to reopen in this doesn't work as expected.
