### ISSUE TITLE
[bindery-continuation] Consider reworking how margin removal is handled

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#5]
If a grid of items (e.g., 2-column flexbox div) is continued onto a new page, only the first item of the grid has its top margin removed.

Perhaps check if the continued element has a top-margin and if so get that value and use it to position the entire page negatively from the top?

**Comment by evnbr** [comment]
Can you include an example?

I think bindery should defer as much of this as possible to the user, maybe not removing any margins by default. there are too many ambiguous cases.

**Comment by teddybradford** [comment]
Yeah, on second thought I think removing as many override styles as possible by default would be the best approach. That way people can apply their own stylesheets without the headache of figuring out the CSS specificities.

**Comment by teddybradford** [comment]
You could instead just provide examples for how to remove margins/text-indents in the docs.

**Comment by evnbr** [comment]
Yeah. I do want to have good defaults though. Here's a proposal: Let you specify classnames for pieces of a split element. By default, include a rule that sets un-sets indentation for paragraphs.

It could look something like this, though with more descriptive names:

```js
Bindery.Continuation({
  selector: 'p',
  continuesAtEnd: '.continues',
  breaksAtBegin: '.is-continuation' 
});
```

```css
p {
  text-indent: 1.5rem;
  margin: 1.5rem 0;
}

p.continues {
  margin-bottom: 0;
}

p.is-continuation {
  margin-top: 0;
  text-indent: 0;
}
```

**Comment by teddybradford** [comment]
Looks good to me. 👍

**Comment by evnbr** [comment]
You can now provide your own styling for continuations: see example #7 https://github.com/evnbr/bindery/tree/master/example/7_custom_continuation
