### ISSUE TITLE
Printing with crop marks not centred in the page

### ISSUE THREAD

**Issue by caccialdo** [evnbr/bindery#56]
Hi,

I noticed that when trying to print with crop marks, the print area's left edge gets aligned with the page's left edge and the left horizontal crop marks are inexistent.

I'm guessing this is by design but was wondering whether there could be a way to have the print area centred inside the page?

**Comment by evnbr** [comment]
Hi @caccialdo, do you have a screenshot or repro? Crop marks are generally intended to be centered when the paper size is large enough to fit them.

**Comment by evnbr** [comment]
oh my mistake, spreads are centered when booklet printing, but individual pages are not. Will take a look, thanks!

**Comment by evnbr** [comment]
Crop marks are centered by default as of 2.2.8, please reach out if you run into anything else.

**Comment by caccialdo** [comment]
Thanks for chasing this up!
