### ISSUE TITLE
Lists split across multiple pages are missing their bullets starting on the second page

### ISSUE THREAD

**Issue by doersino** [evnbr/bindery#62]
This bug seems like it's been introduced in dc76ef2: the `list-style` should only be set to `none` for `li.continuation:first-child` – not, as it's currently implemented, for any element matching `.continuation`, which happens to include the `ul` or `ol` that's been continued from the previous page.

**Comment by evnbr** [comment]
thanks for catching!

**Comment by evnbr** [comment]
should be fixed by https://github.com/evnbr/bindery/commit/a983e556e9ca5cc592848e533ec62cbe2f1c5539 , please reopen if you run into any issues.
