### ISSUE TITLE
Hyphenation

### ISSUE THREAD

**Issue by edi0th** [evnbr/bindery#69]
Hi ! 
Thanks for Bindery, it's a perfect script for html book layouting !
I was nevertheless concerned with hyphenations. I'm using chromium to render the book (sometimes it's a bit buggy in firefox), but the css hyphenation rules are not working on chromium + linux.

Is there a way I could hyphenize my text, maybe through something like Hyphenator.js ?
Is there a way to do some text processing while the book is being generated ?

Thanks in advance !

**Comment by evnbr** [comment]
Hi @edi0th ,

Bindery should support any CSS option— if you have an example of hyphens working in a website but not in bindery, let me know. I'm not familiar with third party JS hyphenation libraries. If all they are doing is inserting soft hyphens, you could just make sure they run on the your content before you call bindery.makeBook?
