### ISSUE TITLE
Keep rule

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#8]
It would be really awesome to have a keep rule that takes an array of selectors and tries to keep them together. For example: given `[h1, p]` if a break would normally occur after `h1`, bindery should try to avoid that break if the following element is `p`, and instead put the break before the `h1` element.

**Comment by evnbr** [comment]
Yeah, I could certainly see the use for this. Before I figure out how to implement this, would any of these achieve the effect better or worse?
1. CSS Regions had a `break-after: avoid` rule, which would be applied to one element, ie the `h1` in your example.
2. If the whole post was wrapped together, you could just apply PageBreak({ position: 'avoid' }), but that may not be clear.
3. You could avoid the issue with PageBreak({ position: 'before' }), but I don't imagine that's the effect you wanted.

**Comment by teddybradford** [comment]
I'm not sure those would really work for this.

I'm interested in parity with [InDesign's keep options](https://helpx.adobe.com/indesign/using/formatting-paragraphs.html#control_paragraph_breaks_using_keep_options), though that seems like it would be pretty complicated to implement.

Just being able to set rules for keeping sibling elements together would go a long way, I think. It can be awkward for a heading to start at the end of a page, and I'm looking for a way to prevent that without inserting a full page break before each of the titles.

**Comment by teddybradford** [comment]
Being able to select sibling wildcard (*) elements would be useful, too.
e.g., `h1 + *`

**Comment by evnbr** [comment]
Hmm, fair. I guess I'm trying to figure out why it has to depend on both elements. Are there situations where you have a heading style, and *do* want there to be a page break after it? Like [h2 + p] should stay together, but [h2 + figure] should not? (that seems unlikely but i am open to being convinced).

I'm considering whether it's worthwhile to mirror CSS proposal docs, ie https://developer.mozilla.org/en-US/docs/Web/CSS/break-after

**Comment by teddybradford** [comment]
I think as long as PageBreak rules override the Keep rules, there is no need to be able to specify specific elements. For example, if there is a Keep rule created for `h2` elements, and a PageBreak rule set to break before `.gallery` elements, then `h2 + *` would always be kept on the same page unless `*` is a `.gallery`.

**Comment by teddybradford** [comment]
Is this valid?
`Bindery.PageBreak({ selector: "h1, h1 > *", position: "avoid" }),`

**Comment by evnbr** [comment]
Closing to track in regionize repo
