### ISSUE TITLE
Using the RunningHeader for bottom of page

### ISSUE THREAD

**Issue by tredition** [evnbr/bindery#94]
The documentation states the following:

"Keep in mind you can also use multiple RunningHeaders to create multiple elements— for example, to add both a page number at the bottom and a chapter title at the top."

Is there an example on how to do this? By only using RunningHeader two times, it will still displayed at the top of the page. How is it possible to set it to the top and to the bottom of the page?

**Comment by evnbr** [comment]
Oops sorry about that @tredition, that documentation is inaccurate. Adding a second running header clobbers the original one. (This is a feature bindery _should_ have, it was just never implemented).

However, it's not too complicated to write a custom rule to add a second running header— although you'll need to position it manually. Here's an example you can modify to get you started. I added some comments about what's going on. Let me know if it makes sense!

https://codepen.io/brsev/pen/yLVrwdw
